entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: mabolfathi@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web


api:
  dashboard: true
  insecure: false   # keep false for security

providers:
  docker:
    exposedByDefault: false
    network: web

log:
  level: INFO

accessLog:
  filePath: "/opt/logs/access.log"
  bufferingSize: 100  # optional: for performance, batches log lines
  format: json        # or "common"  or "json"